/// Flutter icons Tigger
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tigger
///      fonts:
///       - asset: fonts/Tigger.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Tigger {
  Tigger._();

  static const _kFontFam = 'Tigger';
  static const _kFontPkg = null;

  static const IconData tiger = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
